controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

vehicle_index:
    path: /vehicules
    controller: App\Controller\VehicleController::index

vehicle_create:
    path: /vehicules/ajouter
    controller: App\Controller\VehicleController::create

availability_create:
    path: /disponibilites/ajouter
    controller: 'App\Controller\AvailabilityController::create'

availability_show:
    path: /disponibilites/{slug}
    controller: App\Controller\AvailabilityController::show
    requirements:
        slug: '[a-z0-9\-]+'

availability_edit:
    path: /disponibilites/{slug}/{id}/modifier
    controller: App\Controller\AvailabilityController::edit
    requirements:
        slug: '[a-z0-9\-]+'
        id: \d+

availability_delete_confirm:
    path: /disponibilites/{slug}/{id}/confirmer
    controller: App\Controller\AvailabilityController::deleteConfirm
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

availability_delete:
    path: /disponibilites/{slug}/{id}/supprimer
    methods: [DELETE]
    controller: App\Controller\AvailabilityController::delete
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

search_availability:
    path: /recherche
    controller: App\Controller\SearchController::searchAvailability
